swagger: '2.0'
info:
  version: '1.0'
  title: Anchor API
  description: "# Introduction\nThis document discusses Klaytn API Service (KAS) Anchor API. Anchor API features functions for sending metadata to prove data reliability and ensuring the reliability of service chain data to the Klaytn main chain.\n\n\n\n\n# Error Codes\n\n## 400: Bad Request\n\n | Code | Messages | \n | --- | --- | \n | 1071010 | data don't exist\n1071615 | its value is out of range; size\n1072100 | same payload ID or payload was already anchored\n1072101 | all configured accounts have insufficient funds | \n\n# Authentication\n\n<!-- ReDoc-Inject: <security-definitions> -->"
  contact: {}
host: anchor-api.klaytnapi.com
basePath: /
securityDefinitions:
  auth:
    type: basic
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /v1/anchor:
    post:
      description: It is used to anchor blockchain data. A preconfigured operator is used to create and manage anchoring transactions.
      summary: AnchorBlock
      tags:
      - Data Anchoring Transaction
      operationId: AnchorBlock
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: body
        in: body
        required: false
        description: ''
        schema:
          $ref: '#/definitions/AnchorBlockRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/AnchorBlockStatus'
          examples:
            application/json:
              status: succeed
          headers: {}
        400:
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              code: 1072101
              message: all configured accounts have insufficient funds
  /v1/operator/{operator-id}/tx:
    get:
      description: >-
        Specify an operator ID to search for a list of transactions that were created by the operator.<p></p>


        ## Size<p></p>


        * The `size` query parameter is optional (minimum = 1, maximum = 1000, default = 100).<br>

        * Submitting negative values result in errors.<br>

        * Submitting zero results in a query with `size=100`, which is the default value.<br>

        * Submitting values greater than 1000 result in queries with `size=1000`, which is the maximum value.<br>
      summary: RetrieveAnchorBlock
      tags:
      - Data Anchoring Transaction
      operationId: RetrieveAnchorBlock
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: size
        in: query
        required: false
        default: 100
        type: integer
        format: int64
        maximum: 1000
        exclusiveMaximum: false
        description: Maximum size of account to search
      - name: cursor
        in: query
        required: false
        type: string
        description: Information on last searched cursor
      - name: from-timestamp
        in: query
        required: false
        type: integer
        format: int64
        description: Timestamp of the start time to be searched (in seconds)
      - name: to-timestamp
        in: query
        required: false
        type: integer
        format: int64
        description: Timestamp of the end time to be searched (in seconds)
      - name: operator-id
        in: path
        required: true
        type: string
        description: Operator account address
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/AnchorTransactions'
          examples:
            application/json:
              cursor: ''
              items:
              - createdAt: 1599142860
                payloadId: c61cc0d0-5878-450e-bec8-bf73d6184798
                transactionHash: 0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
              - createdAt: 1599142859
                payloadId: d4f1a11f-4609-40f5-9d59-2313a5799508
                transactionHash: 0x70f6f6745ad0b0f4ce5908f40d20a1f44bd34871e0428be782d84f9a53ea2ba0
              - createdAt: 1599142857
                payloadId: 48b59825-82b2-4595-abfb-c465112618cc
                transactionHash: 0x3f90cd2e02576fd85572ab76aff49b87b9cf3efb623f34bb8d6354ee1b88869f
              - createdAt: 1599142841
                payloadId: b315de34-52cb-41c0-9383-3260ceafd3b2
                transactionHash: 0x8a73a00f04a1f6e8d8af101487bd35f8dbcce6fcb3ddd95059f42b8f7fbc3345
          headers: {}
        400:
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              code: 1071615
              message: its value is out of range; size
  /v1/operator/{operator-id}/tx/{transaction-hash}:
    get:
      description: Specify a transaction hash value and operator ID to search for a list of transactions that were created by the operator. When creating a transaction, you may check the payload that is added to a transaction.
      summary: GetAnchorBlockByTx
      tags:
      - Data Anchoring Transaction
      operationId: GetAnchorBlockByTx
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: operator-id
        in: path
        required: true
        type: string
        description: Operator account address
      - name: transaction-hash
        in: path
        required: true
        type: string
        description: Transaction hash
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/AnchorTransactionDetail'
          headers: {}
        400:
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              code: 1071010
              message: data don't exist
  /v1/operator/{operator-id}/payload/{payload-id}:
    get:
      description: Specify a payload ID and operator ID to search for a list of transactions that were created by the operator. When creating a transaction, you may check the payload that is added to a transaction.
      summary: GetAnchorBlockByPayloadID
      tags:
      - Data Anchoring Transaction
      operationId: GetAnchorBlockByPayloadID
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: operator-id
        in: path
        required: true
        type: string
        description: Operator account address
      - name: payload-id
        in: path
        required: true
        type: string
        description: Payload ID
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/AnchorTransactionDetail'
          headers: {}
        400:
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              code: 1071010
              message: data don't exist
  /v1/operator:
    get:
      description: >-
        Search for a list of created operators and the settings of each of them.<p></p>


        ## Size<p></p>


        * The `size` query parameter is optional (minimum = 1, maximum = 1000, default = 100).<br>

        * Submitting negative values result in errors.<br>

        * Submitting zero results in a query with `size=100`, which is the default value.<br>

        * Submitting values greater than 1000 result in queries with `size=1000`, which is the maximum value.<br>
      summary: RetrieveOperators
      tags:
      - Operator
      operationId: RetrieveOperators
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: size
        in: query
        required: false
        default: 100
        type: integer
        format: int64
        maximum: 1000
        exclusiveMaximum: false
        description: Maximum size of account to search
      - name: cursor
        in: query
        required: false
        type: string
        description: Information on last searched cursor
      - name: from-timestamp
        in: query
        required: false
        type: integer
        format: int64
        description: Timestamp of the start time to be searched (in seconds)
      - name: to-timestamp
        in: query
        required: false
        type: integer
        format: int64
        description: Timestamp of the end time to be searched (in seconds)
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Operators'
          examples:
            application/json:
              cursor: ''
              items:
              - createdAt: 1600156363
                operator: 0x36C144b998FbEF7faf092b01815194a18e1a1163
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
              - createdAt: 1600156362
                operator: 0xfD522BE38Ae3Ec4F84A7A411A9e2b3Aee81317b5
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
              - createdAt: 1600156361
                operator: 0xA54579E74e4709600AA7fb91D4cfefb1aECFF9ee
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
              - createdAt: 1600156360
                operator: 0xBBe7d40917d99eF1581b3abc7cdA69492C860F1F
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
              - createdAt: 1600156359
                operator: 0xc72408058DAC1343B8C99Ca90Cb58Ea89637C1eE
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
              - createdAt: 1600156351
                operator: 0x8f315315F90B0b3dEA038FC659F07bac62Fcb2f6
                setting:
                  useGlobalFeePayer: true
                  useOperator: true
          headers: {}
        400:
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              code: 1071615
              message: its value is out of range; size
  /v1/operator/{operator-id}:
    get:
      description: Search for the settings of a specific operator.
      summary: GetOperator
      tags:
      - Operator
      operationId: GetOperator
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-chain-id
        in: header
        required: true
        type: string
        description: Klaytn chain network ID (1001 or 8217)
      - name: operator-id
        in: path
        required: true
        type: string
        description: Operator account address
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Operator'
          headers: {}
definitions:
  AnchorBlockStatus:
    title: AnchorBlockStatus
    description: Anchoring state response
    type: object
    properties:
      status:
        description: Anchoring success/failure
        example: succeed
        type: string
    required:
    - status
  ErrorResponse:
    title: ErrorResponse
    description: This response contains error description.
    type: object
    properties:
      code:
        description: Service code (first 3 digits) and error code (last 4 digits)
        example: 1072101
        type: integer
        format: int64
      message:
        description: Error message
        example: all configured accounts have insufficient funds
        type: string
    required:
    - code
    - message
  AnchorBlockRequest:
    title: AnchorBlockRequest
    description: Anchor block request schema
    type: object
    properties:
      operator:
        description: Operator account address
        example: 0x426Cd8fF0672225c7e96E0bD2f9175B05790653d
        type: string
      payload:
        description: Anchor data. ID is set to SHA256 (payload) by default if an ID is not provided. It receives a string-type ID value and determines that it is not set if it is not a string type.
        type: object
        additionalProperties:
          type: object
    required:
    - operator
    - payload
  AnchorTransactions:
    title: AnchorTransactions
    description: List of anchoring transactions
    type: object
    properties:
      cursor:
        description: Cursor information on last searched location
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/AnchorTransaction'
    required:
    - cursor
  AnchorTransaction:
    title: AnchorTransaction
    description: Anchoring transaction information
    type: object
    properties:
      createdAt:
        description: Anchoring transaction creation time
        example: 1599142860
        type: integer
        format: int64
      payloadId:
        description: Payload ID
        example: c61cc0d0-5878-450e-bec8-bf73d6184798
        type: string
      transactionHash:
        description: Transaction hash of anchoring transaction
        example: 0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
        type: string
    required:
    - createdAt
    - payloadId
    - transactionHash
  AnchorTransactionDetail:
    title: AnchorTransactionDetail
    description: Anchoring transaction information
    type: object
    properties:
      payload:
        description: Anchor data. ID is set to SHA256 (payload) by default if an ID is not provided. It receives a string-type ID value and determines that it is not set if it is not a string type.
        type: object
        additionalProperties:
          type: object
      transactionHash:
        description: Transaction hash of anchoring transaction
        example: 0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
        type: string
    required:
    - payload
    - transactionHash
  Operators:
    title: Operators
    description: List of operators
    type: object
    properties:
      cursor:
        description: Cursor information on last searched location
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/Operator'
    required:
    - cursor
  Operator:
    title: Operator
    description: Operator information
    type: object
    properties:
      createdAt:
        description: Operator creation time
        example: 1600156363
        type: integer
        format: int64
      operator:
        description: Operatorâ€™s Klaytn account address
        example: 0x36C144b998FbEF7faf092b01815194a18e1a1163
        type: string
      setting:
        $ref: '#/definitions/OperatorSetting'
    required:
    - createdAt
    - operator
  OperatorSetting:
    title: OperatorSetting
    description: Operator payment information
    type: object
    properties:
      useGlobalFeePayer:
        description: Global fee delegation account enabled/disabled
        example: true
        type: boolean
      useOperator:
        description: Operator payment enabled/disabled
        example: true
        type: boolean
    required:
    - useGlobalFeePayer
    - useOperator
security:
- auth: []
tags:
- name: Data Anchoring Transaction
  description: ''
- name: Operator
  description: ''
